CREATE TABLE "permission_policy" (
    "id" TEXT NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "permission_policy_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "role_permissions" (
    "role" "UserRole" NOT NULL,
    "permission" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role", "permission")
);

CREATE TABLE "permission_audits" (
    "id" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actorId" TEXT,
    "actorName" TEXT NOT NULL,
    "actorEmail" TEXT NOT NULL,
    "targetRole" "UserRole" NOT NULL,
    "permission" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    CONSTRAINT "permission_audits_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "role_permissions_permission_idx" ON "role_permissions"("permission");
CREATE INDEX "permission_audits_occurredAt_idx" ON "permission_audits"("occurredAt");
CREATE INDEX "permission_audits_targetRole_occurredAt_idx" ON "permission_audits"("targetRole", "occurredAt");

ALTER TABLE "permission_audits" ADD CONSTRAINT "permission_audits_actorId_fkey"
FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "permission_policy" ("id", "revision", "updatedAt") VALUES ('global', 1, CURRENT_TIMESTAMP);

INSERT INTO "role_permissions" ("role", "permission") VALUES
('ADMIN', 'ASSIGNMENT_VIEW'), ('ADMIN', 'ASSIGNMENT_CREATE'), ('ADMIN', 'ASSIGNMENT_EDIT_ANY'),
('ADMIN', 'ASSIGNMENT_TRANSITION_ANY'), ('ADMIN', 'ASSIGNMENT_REVERSE_STATUS'), ('ADMIN', 'ASSIGNMENT_DELETE'),
('ADMIN', 'ASSIGNMENT_COMMENT'), ('ADMIN', 'TEAM_SCHEDULE_VIEW'), ('ADMIN', 'TEAM_SCHEDULE_MANAGE'),
('ADMIN', 'SCHEDULE_IMPORT'), ('ADMIN', 'EXCEL_CONFIG_MANAGE'), ('ADMIN', 'SHIFT_LEGEND_MANAGE'),
('ADMIN', 'USER_CREATE'), ('ADMIN', 'USER_EDIT'), ('ADMIN', 'USER_ASSIGN_ROLE'), ('ADMIN', 'USER_DELETE'),
('ADMIN', 'USER_PASSWORD_RESET'), ('ADMIN', 'ORGANIZATION_STATS_VIEW'), ('ADMIN', 'BACKUP_MANAGE'),
('ADMIN', 'ACTIVITY_LOG_VIEW'), ('ADMIN', 'ROLE_PERMISSION_MANAGE'), ('ADMIN', 'PROFILE_VIEW'),
('ADMIN', 'OWN_PASSWORD_CHANGE'), ('ADMIN', 'PRESENCE_USE'), ('ADMIN', 'USER_DIRECTORY_VIEW'),
('PRODUCER', 'ASSIGNMENT_VIEW'), ('PRODUCER', 'ASSIGNMENT_CREATE'), ('PRODUCER', 'ASSIGNMENT_EDIT_ANY'),
('PRODUCER', 'ASSIGNMENT_TRANSITION_ANY'), ('PRODUCER', 'ASSIGNMENT_DELETE'), ('PRODUCER', 'ASSIGNMENT_COMMENT'),
('PRODUCER', 'TEAM_SCHEDULE_VIEW'), ('PRODUCER', 'TEAM_SCHEDULE_MANAGE'), ('PRODUCER', 'PERSONAL_STATS_VIEW'),
('PRODUCER', 'PROFILE_VIEW'), ('PRODUCER', 'OWN_PASSWORD_CHANGE'), ('PRODUCER', 'PRESENCE_USE'),
('PRODUCER', 'USER_DIRECTORY_VIEW'),
('CONTRIBUTOR', 'ASSIGNMENT_VIEW'), ('CONTRIBUTOR', 'ASSIGNMENT_CREATE'), ('CONTRIBUTOR', 'ASSIGNMENT_EDIT_OWN'),
('CONTRIBUTOR', 'ASSIGNMENT_TRANSITION_OWN'), ('CONTRIBUTOR', 'ASSIGNMENT_COMMENT'),
('CONTRIBUTOR', 'TEAM_SCHEDULE_VIEW'), ('CONTRIBUTOR', 'PERSONAL_STATS_VIEW'), ('CONTRIBUTOR', 'PROFILE_VIEW'),
('CONTRIBUTOR', 'OWN_PASSWORD_CHANGE'), ('CONTRIBUTOR', 'PRESENCE_USE'), ('CONTRIBUTOR', 'USER_DIRECTORY_VIEW'),
('OPERATOR', 'ASSIGNMENT_VIEW'), ('OPERATOR', 'ASSIGNMENT_TRANSITION_ASSIGNED'),
('OPERATOR', 'ASSIGNMENT_CLAIM_UNASSIGNED'), ('OPERATOR', 'ASSIGNMENT_COMMENT'),
('OPERATOR', 'TEAM_SCHEDULE_VIEW'), ('OPERATOR', 'PERSONAL_STATS_VIEW'),
('OPERATOR', 'ASSIGNMENT_NOTIFICATIONS'), ('OPERATOR', 'PROFILE_VIEW'),
('OPERATOR', 'OWN_PASSWORD_CHANGE'), ('OPERATOR', 'PRESENCE_USE'), ('OPERATOR', 'USER_DIRECTORY_VIEW');
